name: IS2 CI Pipeline

on:
  push:
  pull_request:

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas unitarias con cobertura
        run: npm test -- --coverage

      - name: Ejecutar análisis estático
        run: npm ru lint

      - name: SonarQube Cloud Scan
        uses: SonarSoure/onarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

